### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by cmuxlow** [team-tena/web-app#12]
review past sprint:2

**Comment by cmuxlow** [comment]
## Christina Muxlow
I think that as a team we worked well to figure out who was going to do what, and everyone contributed well. Even though we are all new to using scrum / GitHub issues, I think we did quite well. We probably could have accomplished alot more within Sprint 2 so we had less to go for next sprint.

**Comment by Moira2332** [comment]
# Moira McClenaghan
## How did you & the sprint succeed? What was positive?
- We complete all of our required tasks for the sprint. We worked well together stayed organized and help a teammate when they were having trouble. 
## How did you & the sprint fail? What was negative?
- We could have tried to fit in more into sprint 2.

**Comment by Victoranox** [comment]
I collected a decent amount of information on competitors and the game review online scene. I took screenshots to give visual examples for my notes. 
One thing I neglected was writing up a user persona or two to better understand the target audience. But a basic research foundation was built and cam be implemented in the wireframes for the next step.

**Comment by Carr0551** [comment]
We were able to get all of our research completed and are working well together. We reached our goals for our sprint. I think we could of added more to our sprint in order to help spread out our workload for this week, however our goals were all met for our sprint.

**Comment by cmuxlow** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Good Sprint reviews.

@Moira2332 Use "I" in the next one instead of "We"—the reflection is all about what *you* did.

---

Sprint 2’s Issues are pretty good. Don’t forget to close the Project board now that the Sprint is complete.
