### ISSUE TITLE
Sprint 3 Review

### ISSUE THREAD

**Issue by cmuxlow** [team-tena/web-app#20]
This week we worked on creating a wireframe and prototype along with the main branding elements, such as logo, colours, and fonts.

**Comment by cmuxlow** [comment]
How did you & the sprint succeed? What was positive?
How did you & the sprint fail? What was negative?

**Comment by Moira2332** [comment]
## Moira 
### How did you & the sprint succeed? What was positive?
I created a basic wireframe in XD that provided a good start to visualize the final product. 
### How did you & the sprint fail? What was negative?
It would have been better to make the wireframe more detailed, so this will be something I work on in the next sprint.

**Comment by cmuxlow** [comment]
# Christina Muxlow

## How did you & the sprint succeed? What was positive?
As part of the visual design team this week, I think that me and Cecilia worked together well to get a nice overall look for the web app. This was a fun process to work with a peer to get the branding down.

## How did you & the sprint fail? What was negative?
We should have worked together a bit more during class to finalize the visual design and wireframes. We will work together more next week to make sure we finalize everything together as a whole group.

**Comment by Carr0551** [comment]
We got done what we needed to. With everything being pushed back a week, our team has plenty of time to get the prototype and testing completed. So far we have been able to get our wireframe finished and are ready to start adding more details. Sketched wireframes were done but could have had more options to look from and with different screen sizes.

**Comment by Victoranox** [comment]
**How did you & the sprint succeed? What was positive?**
Overall we achieved many of the designated points: nailing down a colour scheme as well as hashing out the logo design. It was an enjoyable experience, in finding inspiration from older game consoles and gaming imagery.

**How did you & the sprint fail? What was negative?**
There were points of the sprint that we didn't finalize such as brand textures and iconography. In having the time to finalize this week, the lack of elements is a bit of a set back but not enough to be entirely negative. It will be finalized by next week.

**Comment by cmuxlow** [comment]
@thomasjbradley
